apiVersion: v1
kind: Service
metadata:
  name: goodtribes-frontend
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: goodtribes-frontend
  ports:
    - port: {{ .Values.frontend.service.port }}
      targetPort: {{ .Values.frontend.service.port }}
