{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: goodtribes-ingress
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "goodtribes.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.ingress.annotations | nindent 4 }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  rules:
    {{- range .Values.ingress.hosts }}
    - host: {{ . }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: goodtribes-frontend
                port:
                  number: {{ $.Values.frontend.service.port }}
          - path: /admin
            pathType: Prefix
            backend:
              service:
                name: goodtribes-backend
                port:
                  number: {{ $.Values.backend.service.port }}
    {{- end }}
  tls:
    {{- toYaml .Values.ingress.tls | nindent 4 }}
{{- end }}
