apiVersion: apps/v1
kind: Deployment
metadata:
  name: goodtribes-meilisearch
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "goodtribes.labels" . | nindent 4 }}
    app.kubernetes.io/name: meilisearch
spec:
  replicas: {{ .Values.meilisearch.replicaCount }}
  strategy:
    type: Recreate
  selector:
    matchLabels:
      {{- include "goodtribes.selectorLabels" "meilisearch" | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "goodtribes.selectorLabels" "meilisearch" | nindent 8 }}
    spec:
      containers:
        - name: meilisearch
          image: "{{ .Values.meilisearch.image.repository }}:{{ .Values.meilisearch.image.tag }}"
          imagePullPolicy: {{ .Values.meilisearch.image.pullPolicy }}
          ports:
            - containerPort: 7700
              protocol: TCP
          envFrom:
            - secretRef:
                name: goodtribes-secret
          env:
            {{- range $key, $value := .Values.meilisearch.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
          volumeMounts:
            - name: meili-data
              mountPath: /meili_data
          readinessProbe:
            httpGet:
              path: /health
              port: 7700
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 7700
            initialDelaySeconds: 15
            periodSeconds: 20
      volumes:
        - name: meili-data
          persistentVolumeClaim:
            claimName: goodtribes-meilisearch
