apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: goodtribes-minio
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "goodtribes.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.minio.persistence.size }}
  {{- if .Values.minio.persistence.storageClass }}
  storageClassName: {{ .Values.minio.persistence.storageClass }}
  {{- end }}
