apiVersion: v1
kind: Service
metadata:
  name: goodtribes-minio
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "goodtribes.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "goodtribes.selectorLabels" "minio" | nindent 4 }}
  ports:
    - name: api
      port: 9000
      targetPort: 9000
    - name: console
      port: 9001
      targetPort: 9001
