apiVersion: v1
kind: Service
metadata:
  name: goodtribes-postgres
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "goodtribes.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "goodtribes.selectorLabels" "postgres" | nindent 4 }}
  ports:
    - port: {{ .Values.postgres.service.port }}
      targetPort: {{ .Values.postgres.service.port }}
