apiVersion: v1
kind: Service
metadata:
  name: goodtribes-redis
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "goodtribes.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "goodtribes.selectorLabels" "redis" | nindent 4 }}
  ports:
    - port: {{ .Values.redis.service.port }}
      targetPort: {{ .Values.redis.service.port }}
